[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "backend/"

[services.backend.variables]
NODE_ENV = "production"
PORT = "$PORT"

[[services]]
name = "frontend"
source = "frontend/"

[services.frontend.variables]
NODE_ENV = "production"
PORT = "$PORT"
NEXT_PUBLIC_API_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}/api"
